import { Intern } from "./types";

export const mockInterns: Intern[] = [
  {
    id: "HIC001",
    studentName: "Alice Johnson",
    email: "alice.j@university.edu",
    phone: "123-456-7890",
    degree: "B.Tech in Computer Science",
    department: "Engineering",
    college: "State University of Technology",
    hodEmail: "hod.cs@sut.edu",
    internshipType: "Internship",
    submissionDate: "2024-07-20",
    status: "Verified",
    priority: true,
    referralName: "John Doe",
  },
  {
    id: "HIC002",
    studentName: "Bob Williams",
    email: "bob.w@university.edu",
    phone: "234-567-8901",
    degree: "MBA in Marketing",
    department: "Marketing",
    college: "Metropolitan Business School",
    hodEmail: "hod.mkt@mbs.edu",
    internshipType: "Project",
    submissionDate: "2024-07-19",
    status: "Pending",
    priority: false,
    referralName: "Jane Smith",
  },
  {
    id: "HIC003",
    studentName: "Charlie Brown",
    email: "charlie.b@university.edu",
    phone: "345-678-9012",
    degree: "B.E. in Mechanical",
    department: "R&D",
    college: "Institute of Engineering",
    hodEmail: "hod.mech@ioe.edu",
    internshipType: "Internship",
    submissionDate: "2024-07-19",
    status: "Pending",
    priority: true,
    referralName: "John Doe",
  },
  {
    id: "HIC004",
    studentName: "Diana Prince",
    email: "diana.p@university.edu",
    phone: "456-789-0123",
    degree: "B.A. in Human Resources",
    department: "Human Resources",
    college: "City College",
    hodEmail: "hod.hr@citycollege.edu",
    internshipType: "Internship",
    submissionDate: "2024-07-18",
    status: "Rejected",
    priority: false,
    referralName: "Emily White",
  },
  {
    id: "HIC005",
    studentName: "Ethan Hunt",
    email: "ethan.h@university.edu",
    phone: "567-890-1234",
    degree: "M.Sc in Data Analytics",
    department: "IT",
    college: "State University of Technology",
    hodEmail: "hod.ds@sut.edu",
    internshipType: "Project",
    submissionDate: "2024-07-17",
    status: "Verified",
    priority: true,
    referralName: "Jane Smith",
  },
  {
    id: "HIC006",
    studentName: "Fiona Glenanne",
    email: "fiona.g@university.edu",
    phone: "678-901-2345",
    degree: "B.Com in Finance",
    department: "Finance",
    college: "Metropolitan Business School",
    hodEmail: "hod.fin@mbs.edu",
    internshipType: "Internship",
    submissionDate: "2024-07-16",
    status: "Pending",
    priority: false,
    referralName: "Peter Jones",
  },
];

export const reportData = [
  { name: 'Engineering', value: 25 },
  { name: 'Marketing', value: 15 },
  { name: 'R&D', value: 20 },
  { name: 'HR', value: 10 },
  { name: 'IT', value: 18 },
  { name: 'Finance', value: 12 },
];
